### PR TITLE
Try to read all pymssql.connect kwargs from config

### PR DESCRIPTION
**Pull request by piotch**
This allows to use the config file to pass arguments such as `port` or `timeout`.

### CODE REVIEW

**Comment by rtrox** [comment]
LGTM, thanks!

**Comment by rtrox** [comment]
Making a quick PR to bump the version and fix pypi_deploy via travis. Once complete, I'll merge this to master and deploy to pypi.

Thanks again @piotch !

**Comment by piotch** [comment]
Great! thank you :)

**Comment by rtrox** [comment]
@piotch your changes are deployed to prod pypi, thanks again!

**Pull request merged**
