### PR TITLE
Added a docstring to template_query

### PR DESCRIPTION
**Pull request by sambozek**
Added a concatenated docstring as to your specifications.

### CODE REVIEW

**Comment by rtrox** [comment]
Fixes #57.

Thanks for the PR, @sambozek !

**Comment by rtrox** [comment]
Ah @sambozek, it looks like this PR was actually sent to the issue_53 branch, rather than master. Can you please open another PR against my master branch?

Thanks!

**Comment by sambozek** [comment]
Hey @rtrox do you still need me to do anything. Saw that #64 properly merged it. 

If not, thanks for letting me know how to improve my future pull requests!

**Comment by rtrox** [comment]
Nope, thanks @sambozek, we're all good!

On Wed, Oct 26, 2016, 9:03 PM Sam Bozek <notifications@github.com> wrote:

Hey @rtrox <https://github.com/rtrox> do you still need me to do anything.
Saw that #64 <https://github.com/rtrox/mssqlcli/pull/64> properly merged
it.

If not, thanks for letting me know how to improve my future pull requests!

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/rtrox/mssqlcli/pull/58#issuecomment-256527191>, or mute
the thread

**Pull request merged**
