### PR TITLE
Add flake8 to tox and TravisCI tests.

### PR DESCRIPTION
**Pull request by Ayrx**
Ref #9

### CODE REVIEW

**Comment by Ayrx** [comment]
Do you want the pep8 fixes in the same PR?

**Comment by rtrox** [comment]
Hey Aryx! Thanks for throwing this together! I probably should have assigned this issue to myself, as I knew there was going to be several pep8 issues to fix once testing was introduced.

I've created #19 to track them, and I'll complete them this morning so that we can merge this.

Thanks for the another great PR!

**Comment by Ayrx** [comment]
✨✨ ✨

**Comment by rtrox** [comment]
@Ayrx - pep8 fixes are complete, would you mind rebasing so we can re-run the tests and get this merged?

Thanks!

**Comment by Ayrx** [comment]
Done!

**Comment by rtrox** [comment]
Hrm, looks like we're still getting 3 errors from `flake8-import-order` (that's a new one by me, btw):
```
./mssqlcli/cli.py:18:1: I201 Missing newline before sections or imports.
./mssqlcli/config.py:18:1: I201 Missing newline before sections or imports.
./mssqlcli/config.py:19:1: I201 Missing newline before sections or imports.
```

They don't show up locally:
```
mssqlcli [ flake8 .  
mssqlcli [ python3 -m flake8 .
```

**Comment by Ayrx** [comment]
Ah sorry, it's a flake plugin I was using it my other projects. Let me remove it from the config!

**Comment by rtrox** [comment]
Hey @Ayrx - I'm good either way, I'm just a bit perturbed that the plugin seems to be behaving different locally than on TravisCI.

If the same three errors show for you locally with the tox config then I'm good with fixing the errors and merging, I just don't like the idea of locally tests and remote tests not matching :-)

Thanks!

**Comment by Ayrx** [comment]
@rtrox That's because you were probably running flake8 outside of tox (where I was pulling the extra plugin in the `deps` section). If you had invoked the test with tox it _should_ show the errors as well.

**Comment by rtrox** [comment]
It looks like the switch back to running tox in travis rather than coverage broke coveralls. I think this should be fixable with the following changes:

**Comment by Ayrx** [comment]
Let's see if that fixes it!

**Comment by rtrox** [comment]
Hey @Ayrx,

It looks like the coverage command that you passed isn't correct:

https://travis-ci.org/rtrox/mssqlcli/jobs/169764929
```
E   SystemExit: usage: pytest.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...
E      or: pytest.py --help [cmd1 cmd2 ...]
E      or: pytest.py --help-commands
E      or: pytest.py cmd --help
E   
E   error: no commands supplied
```

seems to work correctly with the following invocation:
`coverage run -m pytest --strict mssqlcli`

**Comment by rtrox** [comment]
Hey @Ayrx,

I made a PR to your branch which appears to resolve the coveralls issue. It also reintroduces the (now passing) import-order tests.

Thanks again for the work on this!

**Comment by rtrox** [comment]
LGTM,  Merging.  Thanks Again,  @Ayrx!

**Pull request merged**
